language: c
compiler:
#    - clang
    - gcc
os:
    - linux
#    - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
#    - llvm-toolchain-precise-3.8
    packages:
    - gcc-6
#    - clang-3.8
script:
    - ./autogen.sh
    - mkdir build
    - cd build
    - ../configure CFLAGS="-std=c11 -Wall" && make
    - cd test
    - make check
